# Generated by Django 5.1.4 on 2024-12-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.TextField()),
                ('image_name', models.TextField()),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
