# Generated by Django 5.1.4 on 2024-12-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='destination',
            name='review',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='destination',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
