# Generated by Django 5.1.4 on 2024-12-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_destination_days_destination_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image_name',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
